<?php
// $Id$

/**
 * Implementation of hook_theme()
 */
function nodeformcols_theme($aExisting) {
  return array(
    // This needs to run after node.module's hook_theme(), which we ensure
    // by setting this module's weight to 1 during install.
    'node_form' => array(
      'template' => 'node-form',
    ),
    'nodeformcols_configuration' => array(
      'template' => 'nodeformcols-configuration',
      'arguments' => array('element'=>array()),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function nodeformcols_menu() {
  $items = array();
  
  if (!defined('MAINTENANCE_MODE')) {
    foreach (node_get_types() as $type) {
      $type_name = $type->type;
      $type_url_str = str_replace('_', '-', $type_name);
      $items['admin/content/node-type/'. $type_url_str .'/form'] = array(
        'title' => 'Manage form',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('nodeformcols_configuration_form', $type_name),
        'access arguments' => array('administer content types'),
        'file' => 'nodeformcols.admin.inc',
        'type' => MENU_LOCAL_TASK,
        'weight' => 3
      );
    }
  }
  
  return $items;
}

function nodeformcols_form_regions() {
  return array(
    'main' => t('Main'),
    'right' => t('Right'),
    'footer' => t('Footer'),
  );
}

/**
 * Gets default placements for standard fields
 *
 * @return array
 */
function _nodeformscols_default_field_placements() {
  return array(
    'title' => array('region' => 'main'),
    'body_field' => array('region' => 'main'),
    'menu' => array('region' => 'right'),
    'revision_information' => array('region' => 'right'),
    'comment_settings' => array('region' => 'right'),
    'path' => array('region' => 'right'),
    'options' => array('region' => 'right'),
    'author' => array('region' => 'right'),
  );
}

function nodeformscols_field_placements($content_type) {
  return variable_get('nodeformscols_field_placements_' . $content_type, _nodeformscols_default_field_placements());
}

function nodeformscols_content_extra_fields($type_name) {
  return array(
    'buttons' => array(
      '#title' => t('Buttons'),
      '#description' => t('Save, preview and delete buttons.'),
      '#weight' => 50,
    ),
    'options' => array(
      '#title' => t('Workflow options'),
      '#description' => t('Options for publishing, sticky and publish on front page.'),
      '#weight' => 0,
    ),
  );
}

/**
 * Preprocess function to run ahead of other modules.
 */
function template_preprocess_node_form(&$aVars) {
  drupal_add_css(drupal_get_path('module', 'nodeformcols') . '/css/nodeformcols.css');
  
  $form = &$aVars['form'];
  
  $regions = array();
  $weight = 0;
  foreach (nodeformcols_form_regions() as $name => $title) {
    $regions[$name] = array(
      '#prefix' => '<div class="form-region-' . $name . '">',
      '#suffix' => '</div>',
      '#weight' => $weight,
    );
    $weight++;
  }

  $placements = nodeformscols_field_placements($form['#node']->type);

  foreach ($form as $key => $field) {
    if (substr($key, 0, 1)=='#' || substr($key, 0, 8)=='section_' || 
        $field['#type']=='value' || $field['#type']=='hidden'|| $field['#type']=='token') {
      continue;
    }
    
    if (isset($placements[$key])) {
      $p = $placements[$key];
      
      if (isset($p['weight'])) {
        $field['#weight'] = $p['weight'];
      }
      if (isset($p['collapsed'])) {
        $field['#collapsed'] = $p['collapsed'];
      }
      $regions[$p['region']][$key] = $field;
      unset($form[$key]);
    }
    else {
      $regions['footer'][$key] = $field;
      unset($form[$key]);
    }
  }
  
  
  foreach ($regions as $name => $def) {
    $form['nodeformcols_region_' . $name] = $def;
  }
}
